// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMTC6_Qg1Iv6gKUDC5WutqwEFZWw67yAU',
    appId: '1:865776533202:web:f5b738825f85618602b70b',
    messagingSenderId: '865776533202',
    projectId: 'apcsa-quiz-app-7ddec',
    authDomain: 'apcsa-quiz-app-7ddec.firebaseapp.com',
    storageBucket: 'apcsa-quiz-app-7ddec.appspot.com',
    measurementId: 'G-HP4N59N839',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARg4rgM_RQHgMJ91PxlcHlPo57ZIU1brI',
    appId: '1:865776533202:android:fdef8e4a984cf84402b70b',
    messagingSenderId: '865776533202',
    projectId: 'apcsa-quiz-app-7ddec',
    storageBucket: 'apcsa-quiz-app-7ddec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuAcdw88CacZiK91yXIc97bs-suN1wQpc',
    appId: '1:865776533202:ios:d7e178ed5af4379702b70b',
    messagingSenderId: '865776533202',
    projectId: 'apcsa-quiz-app-7ddec',
    storageBucket: 'apcsa-quiz-app-7ddec.appspot.com',
    iosClientId: '865776533202-20lvc0shjed2f6p4hfk3gppbieg8a1oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.apcsaQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuAcdw88CacZiK91yXIc97bs-suN1wQpc',
    appId: '1:865776533202:ios:d7e178ed5af4379702b70b',
    messagingSenderId: '865776533202',
    projectId: 'apcsa-quiz-app-7ddec',
    storageBucket: 'apcsa-quiz-app-7ddec.appspot.com',
    iosClientId: '865776533202-20lvc0shjed2f6p4hfk3gppbieg8a1oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.apcsaQuiz',
  );
}
